### ISSUE TITLE
客户端离线无法正常显示

### ISSUE THREAD

**Issue by tanglu1323123** [eastarpen/ping-charts#2]
当客户端离线时，无法向服务端发送数据
服务端的做法似乎并不是空着或者显示超时，而是将所有收到的数据包按照等时间间隔处理
我想应该是服务端将未接受到的数据计为超时 并显示在图形化界面上

**Comment by eastarpen** [comment]
> 服务端的做法似乎并不是空着或者显示超时，而是将所有收到的数据包按照等时间间隔处理

设计之初没考虑 client 和 sever 的连通性

[server 查询逻辑](https://github.com/eastarpen/ping-charts/blob/9c6c1f9a54da627b53c600378f97bbbe8ff00e2c/server/src/lib/database.py#L111) 是直接获取数据库中 X min 之前到 "现在" 的所有数据

如果 client 长时间未发送数据, server 确实没有任何反馈机制

因为 上传数据的间隔完全由 client 决定(在一键脚本中由 systemd timer 控制)。

~~虽然在 server 端可以强行加入定时校验机制~~

**短时间内不考虑这个机制**

**Comment by eastarpen** [comment]
欢迎提出想法或 PR
