### ISSUE TITLE
server 1.2.2 一点问题

### ISSUE THREAD

**Issue by tanglu1323123** [eastarpen/ping-charts#6]
以我搭建的 https://status.blogcdn.net 为例

1、当延时大于100ms时，绿色节点状态的会将丢包信息遮盖一部分，我想可能对色盲群体有些不友好
2、底部的拖动条不明显，用户很容易忽略第四个监测节点(香港)
3、最长查看周期只有近一周，我还想着查看一年乃至永久状态 哈哈

![image](https://img.tanglu.me/2023/09/11/hhx3wm.webp)

另外中英文并不完全一样，比如 setup 含 update，而setup-zh 不含update
一些脚本文件没有直接展示直链，建议换成直链，如 ：
![image](https://img.tanglu.me/2023/09/11/i8ejir.webp)

**Comment by tanglu1323123** [comment]
我觉得可以做个下拉列表，这样选择性更多一些

点击 `select time` 出现类似这种
![image](https://img.tanglu.me/2023/09/11/iesbar.webp)

**Comment by eastarpen** [comment]
首先感谢反馈

> 当延时大于100ms时，绿色节点状态的会将丢包信息遮盖一部分

目前这个信息的展示依赖于 canvas 元素, 也就是说只能显示在图表中

之后会重写

> 底部的拖动条不明显  
> 中英文并不完全一样

会做出调整, 感谢反馈

> 最长查看周期只有近一周  

考虑数据取样和性能做出的决定

**数据取样** 

对一张图查询的数据大约是 [250 条](https://github.com/eastarpen/ping-charts/blob/d0d2f12c68015047265f069e315f12f40e2c646e/server/src/lib/database.py#L9C1-L10C2), server 先采用简单取样获取数据

前端渲染图表的时候如果数据过多也会再次取样

**性能**

> 一些脚本文件没有直接展示直链，建议换成直链，如 

那些链接是通过相对路径连接的, 目的是始终指向最新的内容

直链后续维护比较麻烦

假设有 10 个 client, 4 个 target, 默认一分钟上传一次, 一天的数据量为

57,600 = 10 * 4 * (24 * 60)

目前做法是保留七天以内的数据, 可以通过 `server --delete` 修改

但前端没有做适配, 后续可以加上

> 一些脚本文件没有直接展示直链

那些链接采用相对路径指向最新版本

直链维护比较麻烦

**Comment by tanglu1323123** [comment]
> 对一张图查询的数据大约是 [250 条](https://github.com/eastarpen/ping-charts/blob/d0d2f12c68015047265f069e315f12f40e2c646e/server/src/lib/database.py#L9C1-L10C2), server 先采用简单取样获取数据
> 
> 前端渲染图表的时候如果数据过多也会再次取样

现在统计是什么样的呀，比如一天 是计算每5分钟的平均丢包率吗？

> 那些链接采用相对路径指向最新版本
> 
> 直链维护比较麻烦

github提供的直链是跟着你的文件一起变的吧，如：
https://raw.githubusercontent.com/eastarpen/ping-charts/master/scripts/server.sh

**Comment by eastarpen** [comment]
> 现在统计是什么样的呀，比如一天 是计算每5分钟的平均丢包率吗？

No, 默认情况 client 一分钟统计一次

每调用一次 client, client 会把所有预配置的 target ping 一遍 获得 delay 和 loss, 然后上传 server

server 将数据写入数据库

前端请求时, server 直接查询数据库

若数据低于 250条, 直接返回数据, 若高于250条, 取样

一条数据格式如下

`clientId, targetId, timestamp, loss, delay`

> github提供的直链是跟着你的文件一起变的吧

got

**Comment by tanglu1323123** [comment]
> 

我知道每分钟会上传数据，
因为一天是 12*24=250分钟，我想知道表中每个数据是不是对每5或者6分钟的数据做平均处理，计算出那个时间段的丢包率

**Comment by eastarpen** [comment]
No.

目前查询数据的时候不涉及任何计算

图中的 "每一根线" 代表一条数据, 默认情况代表那一分钟的数据

你可以观察你的demo, (5min, 30min, 1h, 3h) 他们表上显示的时间是连续的(后一个比前一个多一分钟)

(1d, 7d)则不连续

**Comment by tanglu1323123** [comment]
> 

那既然不涉及计算 有什么不好展示的
完全可以将所有时间段平均挑选250份

而且我觉得应该涉及计算

**Comment by eastarpen** [comment]
> 完全可以将所有时间段平均挑选250份

目前就是这么做的

> 那既然不涉及计算 有什么不好展示的

没有理解, 你是在说 "为什么选择不展示长时间的数据吗"

之前说过 出于性能考虑和取样问题

默认情况下 10 clients, 4 targets 能产生 5w 条数据

100天就是 500w, 这会给服务器带来极大的存储和运算压力

**Comment by eastarpen** [comment]
滚动条问题已改善(v1.3.0)

时间选择功能和长期数据问题等待项目重构

**Comment by tanglu1323123** [comment]
> 没有理解, 你是在说 "为什么选择不展示长时间的数据吗"

嗯
我看了下 一天6w条数据 消耗 gb5跑分大概150分 时常大概为2秒，确实对服务器有一定压力

我觉得到时候设计 `时间选择功能和长期数据问题等待项目重构` 可以像 `-p` 一样 加个参数 手动设置服务端可选择最大区间 比如7天 1个月 等

**Comment by eastarpen** [comment]
> 像 -p 一样 加个参数 手动设置服务端可选择最大区间 比如7天 1个月 等

事实上已经加了, --delete 就是 默认保留7天的数据

> 时常大概为2秒

v1.3.0 做了一定性能优化, 可能会有帮助

欢迎测试反馈bug

**Comment by tanglu1323123** [comment]
> 我觉得到时候设计 时间选择功能和长期数据问题等待项目重构 可以像 -p 一样 加个参数 手动设置服务端可选择最大区间 比如7天 1个月 等

我的意思是这样，设置之后就不能从9月1号到10月10号，而不是数据只保留近七天
![](https://camo.githubusercontent.com/7a704efa15bc890d178dd526086ab165ff7034eb8d814690fc5b8ef1de7168d1/68747470733a2f2f696d672e74616e676c752e6d652f323032332f30392f31312f6965736261722e77656270)
