### ISSUE TITLE
域名和IP测试结果不一样

### ISSUE THREAD

**Issue by tanglu1323123** [eastarpen/ping-charts#7]
我有两台机器都出现了域名测的延时远高于IP
```
- id: 1
  name: name
  port: 80
  addr: dianxin..test.com
```

我测试ping dianxin.test.com对应的IP显示延时正常，我在itdog进行tcping延时也正常
但是如果我用域名的话，延时就会很快升高，不清楚为什么

![image](https://img.tanglu.me/2023/11/23/ks4qel.webp)

**Comment by eastarpen** [comment]
因为域名解析的时间会算在延时内, 多出的那段时间应该是域名查询时间

感谢反馈

**Comment by tanglu1323123** [comment]
我另一台机器就是图中的 137.*.*.68[19]
机器IP是 137.220.171.68

这台机器电信和联通域名显示正常，但是移动域名就不正常了

**Comment by tanglu1323123** [comment]
我觉得这个例子可以反驳你说的dns解析时间
我四个域名都是用的cf 同一个主域名

**Comment by eastarpen** [comment]
v1.3.1 版本在进行延时测试前会先解析DNS

你可以测试一下是否解决问题

**Comment by tanglu1323123** [comment]
一个好了 一个没好，奇怪

![image](https://img.tanglu.me/2023/11/23/r843i9.webp)

**Comment by tanglu1323123** [comment]
不好意思，我刚刚下载tcping测试了下，确实是172ms
不是ping-chart的问题
